'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Check } from 'lucide-react';

export function ContactPage() {
  const [submitted, setSubmitted] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setSubmitted(true);
  };
  return <main className="contact-page">
    <header className="marketing-nav contact-nav"><Link href="/" className="marketing-logo"><img src="/img/cropped-logo.png" alt="Ashistanto" /></Link><nav><a href="/">Home</a><a href="/about">About</a><a href="/solutions">Solutions</a><a href="/contact" aria-current="page">Contact Us</a></nav><Link href="/login" className="marketing-nav-cta">Get Started <ArrowRight size={13} /></Link></header>
    <section className="contact-hero"><div className="contact-canvas"><div className="contact-heading"><p className="eyebrow">START A CONVERSATION</p><h1>GET IN TOUCH</h1><p>Tell us what you are working on and the right Ashistanto team will respond.</p></div><form className="contact-form contact-form-glass" onSubmit={submit}><div className="contact-field"><label htmlFor="first-name">First name <span>*</span></label><input id="first-name" name="firstName" required /></div><div className="contact-field"><label htmlFor="last-name">Last name <span>*</span></label><input id="last-name" name="lastName" required /></div><div className="contact-field"><label htmlFor="email">Email <span>*</span></label><input id="email" name="email" type="email" required /></div><div className="contact-field"><label htmlFor="phone">Phone <span>*</span></label><input id="phone" name="phone" type="tel" required /></div><div className="contact-field"><label htmlFor="title">Title <span>*</span></label><input id="title" name="title" required /></div><div className="contact-field"><label htmlFor="organisation">Organisation <span>*</span></label><input id="organisation" name="organisation" required /></div><div className="contact-field"><label htmlFor="service">Service interest <span>*</span></label><select id="service" name="service" required><option value="">Select</option><option>AI</option><option>Automation</option><option>Applications</option><option>Data</option><option>Microsoft 365</option></select></div><div className="contact-field"><label htmlFor="solution">Solution interest <span>*</span></label><select id="solution" name="solution" required><option value="">Select</option><option>Customer Intelligence</option><option>Employee Intelligence</option><option>Operational Intelligence</option></select></div><div className="contact-field contact-message"><label htmlFor="message">How can we help?</label><textarea id="message" name="message" rows={5} /></div><div className="contact-consent"><input id="consent" name="consent" type="checkbox" required /><label htmlFor="consent">Ashistanto will use your information in accordance with our <Link href="/privacy">privacy policy</Link> and handle it with care wherever it is processed.</label></div><div className="contact-submit">{submitted ? <div className="contact-success"><Check size={16}/> Thanks — your enquiry has been received.</div> : <button type="submit">Submit enquiry <ArrowRight size={14}/></button>}</div></form></div></section>
    <footer className="marketing-footer contact-footer"><div className="footer-main"><div className="footer-brand"><Link href="/" className="marketing-logo"><img src="/img/cropped-logo.png" alt="Ashistanto" /></Link><small className="footer-byline">An Ashistanto solution by Hosho Digital.</small><div className="footer-socials" aria-label="Hosho Digital social links"><a href="https://www.linkedin.com/company/hoshodigital" target="_blank" rel="noreferrer" aria-label="LinkedIn"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M20.45 20.45h-3.55v-5.57c0-1.33-.03-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.35V9h3.41v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.46v6.28zM5.34 7.43a2.06 2.06 0 1 1 0-4.12 2.06 2.06 0 0 1 0-4.12zM3.56 20.45h3.56V9H3.56v11.45z"/></svg></a><a href="https://x.com/HoshoDigital" target="_blank" rel="noreferrer" aria-label="X"><img src="https://cdn.simpleicons.org/x/ffffff" alt="" /></a><a href="https://www.instagram.com/hoshodigital/" target="_blank" rel="noreferrer" aria-label="Instagram"><img src="https://cdn.simpleicons.org/instagram/ffffff" alt="" /></a><a href="https://www.youtube.com/@HoshoDigital" target="_blank" rel="noreferrer" aria-label="YouTube"><img src="https://cdn.simpleicons.org/youtube/ffffff" alt="" /></a></div></div><div><b>Solutions</b><Link href="/solutions">Ashistanto</Link></div><div><b>Company</b><a href="https://hoshodigital.com" target="_blank" rel="noreferrer">Hosho Digital</a><Link href="/">Home</Link><Link href="/about">About</Link></div></div><div className="footer-bottom"><span>© 2026 HOSHO DIGITAL Pte. Ltd. ALL RIGHTS RESERVED.</span><nav aria-label="Legal"><Link href="/privacy">Privacy Policy</Link><Link href="/accessibility">Accessibility Statement</Link><Link href="/terms">Terms of Use</Link><Link href="/cookies">Cookies Policy</Link></nav></div></footer>
  </main>;
}
